backend:
  name: github
  repo: elianbryan17/site-congregacao
  branch: main

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "pages"
    label: "Páginas"
    files:
      - file: "content/home.md"
        label: "Página Inicial"
        name: "home"
        fields:
          - { label: "Título", name: "title", widget: "string" }
          - { label: "Conteúdo", name: "body", widget: "markdown" }

  - name: "contato"
    label: "Contato"
    files:
      - file: "content/contato.md"
        label: "Informações de Contato"
        name: "contato"
        fields:
          - { label: "Texto", name: "body", widget: "markdown" }

  - name: "agenda"
    label: "Agenda de Cultos"
    files:
      - file: "content/agenda.yml"
        label: "Lista de Cultos"
        name: "agenda"
        fields:
          - label: "Cultos"
            name: "services"
            widget: "list"
            field:
              { label: "Descrição", name: "description", widget: "string" }

  - name: "galeria"
    label: "Galeria de Fotos"
    folder: "content/galeria"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Imagem", name: "imagem", widget: "image" }
      - { label: "Data", name: "date", widget: "datetime" }